/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostel_java;

import java.sql.*;
import javax.swing.JOptionPane;


public class register extends javax.swing.JFrame {
 Connection conn=null;
        PreparedStatement pst=null;
        Statement smt=null;
    public register() {
          
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lmsg = new javax.swing.JLabel();
        Luser = new javax.swing.JLabel();
        Lpass = new javax.swing.JLabel();
        Lrepass = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Txtuser = new javax.swing.JTextField();
        Ppsw = new javax.swing.JPasswordField();
        Prepsw1 = new javax.swing.JPasswordField();
        Ppin1 = new javax.swing.JPasswordField();
        Bregs = new javax.swing.JButton();
        Cpass = new javax.swing.JCheckBox();
        Crepsw = new javax.swing.JCheckBox();
        cpin = new javax.swing.JCheckBox();
        Bback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lmsg.setText("Admin Registration Form");

        Luser.setText("   Username :");

        Lpass.setText("   Password :");

        Lrepass.setText("   Re-enter Password :");

        jLabel1.setText("          PIN :");

        Ppsw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PpswActionPerformed(evt);
            }
        });

        Prepsw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Prepsw1ActionPerformed(evt);
            }
        });

        Ppin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ppin1ActionPerformed(evt);
            }
        });

        Bregs.setText("Register");
        Bregs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BregsActionPerformed(evt);
            }
        });

        Cpass.setText("show password");
        Cpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CpassActionPerformed(evt);
            }
        });

        Crepsw.setText("show password");
        Crepsw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrepswActionPerformed(evt);
            }
        });

        cpin.setText("show pin");
        cpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpinActionPerformed(evt);
            }
        });

        Bback.setText("Back");
        Bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Bback)
                        .addGap(59, 59, 59)
                        .addComponent(Lmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Lpass, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Luser, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(Lrepass, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpin)
                            .addComponent(Txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ppsw, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cpass)
                            .addComponent(Prepsw1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Crepsw)
                            .addComponent(Ppin1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(Bregs, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Lmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Bback)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Luser)
                    .addComponent(Txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lpass)
                    .addComponent(Ppsw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(Cpass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Prepsw1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lrepass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Crepsw)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ppin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpin)
                .addGap(18, 18, 18)
                .addComponent(Bregs)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ppin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ppin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ppin1ActionPerformed

    private void CpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CpassActionPerformed
         if (evt.getSource()==Cpass){
            if(Cpass.isSelected()){
                Ppsw.setEchoChar((char)0);
            }
            else{
                Ppsw.setEchoChar('*');
            }
        }
    }//GEN-LAST:event_CpassActionPerformed

    private void CrepswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrepswActionPerformed
       if (evt.getSource()==Crepsw){
            if(Crepsw.isSelected()){
                Prepsw1.setEchoChar((char)0);
            }
            else{
                Prepsw1.setEchoChar('*');
            }
        }
    }//GEN-LAST:event_CrepswActionPerformed

    private void Prepsw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Prepsw1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Prepsw1ActionPerformed

    private void cpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpinActionPerformed
         if (evt.getSource()==cpin){
            if(cpin.isSelected()){
                Ppin1.setEchoChar((char)0);
            }
            else{
                Ppin1.setEchoChar('*');
            }
        }
    }//GEN-LAST:event_cpinActionPerformed

    private void BbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbackActionPerformed
        this.dispose();
    }//GEN-LAST:event_BbackActionPerformed

    private void BregsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BregsActionPerformed
      String passord = Ppsw.getText();
        System.out.println(passord);
        if(passord.length() < 8){
            JOptionPane.showMessageDialog(null, "Password must contain atleast 8 characters","Error",
                JOptionPane.ERROR_MESSAGE);
        }
        try{ pass passkey = new pass();
            String userName = "root";
            String password = passkey.password;
            String url = "jdbc:mysql://localhost:3306/Hostel_mngmnt";
            Class.forName("com.mysql.cj.jdbc.Driver").getConstructor().newInstance();
             conn = DriverManager.getConnection(url, userName, password);
           String sql="insert into login (User_name,Password) values(?,?)";
           smt=conn.createStatement();
           
           ResultSet rs=smt.executeQuery("select * from manager");
           System.out.println("rs statement");
           pst=conn.prepareStatement(sql);
           pst.setString(1,Txtuser.getText());
           pst.setString(2,Ppsw.getText());
           if(rs.next()){
          String pin1=rs.getString("Pin");
          
          if(pin1.equals(Ppin1.getText()) && Prepsw1.getText().equals(Ppsw.getText()))
          {    pst.executeLargeUpdate();
              System.out.println("registration successful");     
          } else {
              JOptionPane.showMessageDialog(null, "Incorrect PIN or Re-entered password","Error",
                JOptionPane.ERROR_MESSAGE);
               System.out.println("registration failed"); 
              
           }
          }
          
       }
       catch(Exception ex){
           System.out.println(ex);
       }
    }//GEN-LAST:event_BregsActionPerformed

    private void PpswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PpswActionPerformed
       
        
        
    }//GEN-LAST:event_PpswActionPerformed
 public static void main(String args[]){
     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
 }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bback;
    private javax.swing.JButton Bregs;
    private javax.swing.JCheckBox Cpass;
    private javax.swing.JCheckBox Crepsw;
    private javax.swing.JLabel Lmsg;
    private javax.swing.JLabel Lpass;
    private javax.swing.JLabel Lrepass;
    private javax.swing.JLabel Luser;
    private javax.swing.JPasswordField Ppin1;
    private javax.swing.JPasswordField Ppsw;
    private javax.swing.JPasswordField Prepsw1;
    private javax.swing.JTextField Txtuser;
    private javax.swing.JCheckBox cpin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
